### ISSUE TITLE
could I run training from a cloud-based notebook (GPU issue)

### ISSUE THREAD

**Issue by delaroob** [YNCris/SBeA_release#3]
Hello! 
I saw at the config requirements that I would need 128GB RAM (so I guess I would definitely need a decent GPU). 
Is there any way that I could run the training from something like Google Colab or any kind of cloud-based platform with a GPU? 
(I'm guessing the answer is no, since the labeling and training happen simultaneously and notebooks usually dont allow GUI, but worth a try.)

PS: thank you for your work, it is truly awesome!

**Comment by YNCris** [comment]
Hello! 
Thank you for trying our SBeA. I am sorry that the answer is no. Because SBeA is not an end-to-end artificial neural network model, the configuration in Google Colab is also really difficult. Our development is based on the Ubuntu. Considering the friendly application for biologists, we also took lots of time to debug SBeA on Windows and made the GUI. But we cannot solve that SBeA needs a decent GPU (at least one RTX2080Ti GPU as we tested). 

Our most recent work Anti-drift pose tracker (ADPT): A transformer-based network for robust animal pose estimation cross-species (https://www.biorxiv.org/content/10.1101/2024.02.06.579164v1.abstract) introduces an end-to-end neural network to be potentially used in notebook (We tried using CPU training, slow but can be run). The link is "https://github.com/tangguoling/ADPT". I recommend you try it using Colab for multi-animal tasks.

If you have any other questions, please feel free to contact me. I will try my best to help you to solve them.

**Comment by delaroob** [comment]
Hello again!

Yes, I understand, and thank you so much for your quick reply. 

I can see that ADPT solves this annoying jumping problem in the data, which makes it an attractive choice, but right now I’m trying to make 3D analysis work (thats why SBeA caught my attention aside from it performing really well not just quantification but classification too, all in 3D and with automated calibration like in MouseVenue3D).

Although I’ve tried using SLEAP and DLC, I’m having some issues with the calibration (DLC only supports chessboards with cameras in stereo config, and although SLEAP is compatible with charuco boards, it doesnt track the intersections accurately, so I dont see how the calibration could be accurate…). 
So I guess I will have to use a 3rd party program to calibrate and import it somehow.

Also, it would be great to do the labeling of more camera views simultaneously to save time and improve accuracy (like they do with label3D https://github.com/diegoaldarondo/Label3D), but that would just be extra.

Do you have any suggestions regarding my situation?

**Comment by YNCris** [comment]
Hello again!
In fact, your questions met now are my questions before (about 3 years ago). They are parts of the reasons why we develop SBeA. I recommend you to use pose3d "https://github.com/SwathiSheshadri/pose3d". Some of the parts of pose3d inspired us the 3D reconstruction in BeA, MouseVenue3D, and SBeA. Pose3d uses the chessboard and the code is easy to run. Pose3d can also be combined with DLC.

I also tried Label3D before. I still need to adjust other points in other view angles. It saves little time for me to label the poses. To reduce the number of annotations, it seems SBeA is the first choice. Or would you like to collaborate with our lab to finish your project? You can contact me through my e-mail "yn.han(at)siat.ac.cn".

**Comment by delaroob** [comment]
Hello again!

All right, will give pose3D a shot.

Appreciate the offer, it is very kind of you but I want to make this work in a way that the process could be reproduced consistently. I can see now that this no-GPU-situation is really beginning to limit such research in several ways so maybe it would be wiser to tackle the root of this problem, it can't be avoided much longer now anyway. 

Having said that, I hope to try out this wonderful piece of coding one day and again thank you so much for all your help (and work!) 🙂.
