### ISSUE TITLE
Environment settings for Visual Studio

### ISSUE THREAD

**Issue by 2023Toad** [YNCris/SBeA_release#4]
Thank you for your excellent work. Could you please inform me which version of Visual Studio is utilized for the SBeA tracker?

When attempting to run main.py, I encounter an error in reading configMang module. I have analyzed the dependencies of the eval.pyd file that seems to be causing the error using Dependency Walker. It appears that some files, such as api-ms-win-core-version-l1-1-0.dll, are missing.

I have tried to resolve this by installing the the C++ tools for desktop development and the Windows SDKs via Visual Studio Build Tools 2022 - 17.9.6, and by adjusting the environment variables. This has reduced the number of missing files, but there are still about 10 DLL files.

Any advice you could provide would be greatly appreciated.
Thank you for your time and assistance.

**Comment by YNCris** [comment]
Hello! Thank you trying our SBeA and copying your question here. It is also the first time that this problem happens. I search on the Internet and the reason could be that your Windows lost some core files such as the "api-ms-win-core-version-l1-1-0.dll". You can open the CMD in administrator mode and run "sfc /scannow" to try if it can fix the missing. I think now your problem is in the operating system level. The worst situation is that maybe you should reinstall the operating system to Win10 or Win11.

**Comment by 2023Toad** [comment]
Thank you for your response! I tried both suggestions, but the error persisted. For the time being, I will stop investigating further and consider using other tools. Perhaps I will return to SBeA with a different PC. Thank you again.

**Comment by YNCris** [comment]
Sorry about that. Now only I support the bug fixing of SBeA. It is not like commercial software so it is hard to provide a zero-bug version. Hope you can run other tools on your computer!
