### ISSUE TITLE
can't edit config file, contents get deleted

### ISSUE THREAD

**Issue by delaroob** [YNCris/SBeA_release#6]
## Hi!

I have successfully installed the program, and it finally runs, and I also have .mat calibration files.

However, right after creating a new config file in SBeA, and editing it (specifying path to videos, mouse_num etc.),  instead of saving the config file, it gets deleted + I get some other errors too. Below are my theories and the steps to reproduce.

Thanks in advance for any help!

ps.: I linked the config file contents (in a .txt file) if needed here:
[config_contents.txt](https://github.com/user-attachments/files/16339104/config_contents.txt)

## Here are the steps to reproduce:

**SCENARIO1:** 
in the GUI:

1. click on "Configure": I automatically get the following error

```
Traceback (most recent call last):
File "gui\tab.py", line 80, in tab.MainWindow.event_tab_change
File "gui\info_config.py", line 247, in info_config.InfoConfig.event_b_data_save
File "gui\info_config.py", line 258, in info_config.InfoConfig.event_b_data_save
ValueError: could not convert string to float: '0,90'
```
2. after, if i click on Edit configfile.yaml, it erases the contents of the config file, it is completely empty

**SCENARIO2:** 
in the GUI:

1. click on "Edit configfile.yaml": it opens the config.yaml file (its not empty yet!)
2. edit config file, ctrl+s
3. click on "Configure" (no error yet), then click "Refresh" (still no error)
4. then click on "Load&label&train", aaaand I get the same error again:
```
  File "gui\tab.py", line 80, in tab.MainWindow.event_tab_change
  File "gui\info_config.py", line 247, in info_config.InfoConfig.event_b_data_save
  File "gui\info_config.py", line 258, in info_config.InfoConfig.event_b_data_save
ValueError: could not convert string to float: '0,90'
```

**AFTER BOTH SCENARIOS, WHEN SELECTING THE TRAINING VIDEOS IN THE NEXT PANEL**
the below issue will come up. I guess the config file did not get edited in the end, it really got deleted, so the default parameter for the training video folder `'/home/dltest/sbeaTestEnv/trainvideopath'` stays, and the program tries to insert the selected video after that path (but of course its not there, so it is true that no such file or directory exists)
```
Traceback (most recent call last):
  File "gui\load_files.py", line 245, in load_files.LoadFiles.event_b_click_move_and_load_files
  File "gui\load_files.py", line 265, in load_files.LoadFiles.move_video_files_to_config_path
  File "C:\Users\.conda\envs\sbea\lib\shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\.conda\envs\sbea\lib\shutil.py", line 266, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dltest/sbeaTestEnv/trainvideopath\\rec1-A1-20231224-camera-0.mp4'
```
## Other questions
1. If I'm working on a single animal project, do I need ID data? Or do I just skip that part?
2. What exactly is this "select_rotation" parameter in the config file under T3d_info?
3. I did the calibration in Pose3D, so the .mat output format might be a little bit different than what the program works with. Could you provide an example calibration file? (I checked the demo files, didn't find it)

**Comment by YNCris** [comment]
Hi! Thank you again for your questions! I will answer them one by one.

1. The "Configure" page seems have BUG in your computer. You can directly modify the configfile.yaml using VSCode or any of the text editor.

2. You can skip the page of "Configure". After you edit the configfile.yaml in your project, you can directly jump to the page of "Load&label&train".

3. Yes. It is the same problem of the BUG of "Configure". Skip it and you can get the un-deleted configfile.yaml.

Other questions:
1. I am sorry about that. Our release version of SBeA only supports 2 animals now. If you want to use it on only 1 animal, you can see our previous study "A hierarchical 3D-motion learning framework for animal spontaneous behavior mapping (https://www.nature.com/articles/s41467-021-22970-y)". It is a single animal 3D reconstruction and behavior clustering method. The code link is "https://github.com/huangkang314/Behavior-Atlas".

2. Because the video coordinates should be matched to the world coordinates, we do the matching by choose the foots of animals. The trajectories of the foots are fitted to a plane and all other body parts are rotated according to the position relationships between the plane and the world coordinates. "Select rotation" is the name of the "foots" you defined in the DeepLabCut. 

3. I am sorry that the organizing of the data is a little bit complex. The calibration file is uploaded. You can read the "readme (https://figshare.com/articles/dataset/SBeA_Readme/22315000)" of our data. You can find the .mat file with the segment "caliParas.mat". This is the calibration file.
![image](https://github.com/user-attachments/assets/b184334f-729b-473a-a564-59f25ef18651)

Please feel free to contact me if you have any other questions. I will help you to use our behavior analysis methods until you get your results!

**Comment by delaroob** [comment]
Hi again!

Okay, will do, thank you so much!

About the rotation: what if the animal (…fish) doesn’t have legs?:)

HYN (Yaning Han) ***@***.***> (időpont: 2024. júl. 23., K,
11:48) ezt írta:

**Comment by YNCris** [comment]
Ah I forgot you were using the fish. I think you can label some landmarks such as the angles of your water chamber. These 3D angle points can be regarded as the references for rotation.

**Comment by delaroob** [comment]
Okay!
And for future reference, do all of the animals in the analysis need to be
visible on all of the frames?

HYN (Yaning Han) ***@***.***> (időpont: 2024. júl. 23., K,
13:26) ezt írta:

**Comment by YNCris** [comment]
It will be better that every animal needs to be visible. If it is not, you should write some customized code to process these missing frames. Of course, it is not difficult.
